### ISSUE TITLE
release_stage should not be a bool

### ISSUE THREAD

**Issue by jwoertink** [russ/bugsnag#7]
In this commit `release_stage` was changed to `Bool`, but the Bugsnag API actually wants a String here. This should be the name of the release stage (i.e. "staging", "production", "development", etc...)

https://github.com/russ/bugsnag/commit/27c6ba8e36d47f1bb2e6c7df577bd6f30df1f69e

**Comment by fernandes** [comment]
precisely @jwoertink , @russ do you agree? I can open a PR or we can revert this one

**Comment by jwoertink** [comment]
Yup. I don't think it should be directly reverted. I think the old version used an `Array(String)`, but I think it's just supposed to be `String`. A PR would be cool though!

**Comment by russ** [comment]
@fernandes I’m out on vacation and probably won’t be able to look at this until Thursday. Feel free to submit a PR and I’ll take a look as soon as possible.

**Comment by fernandes** [comment]
@russ first, enjoy your vacation 😄 , when you're back there's a PR waiting for you heheh thank you!

**Comment by jwoertink** [comment]
This is done now!
